name: encrypted_files
description: Cross-platform encrypted file container with streaming decryption.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  sqlite3_flutter_libs: ^0.5.32
  ffi: ^2.1.4
  uuid: ^4.5.1
  collection: ^1.19.1
  intl: ^0.20.2
  file_picker: ^8.3.7
  permission_handler: ^11.4.0
  http: ^1.4.0
  video_player: ^2.9.5
  audioplayers: ^6.4.0
  camera: ^0.11.1
  record: ^6.0.0
  pdfrx: ^1.1.29
  flutter_secure_storage: ^9.2.4
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  equatable: ^2.0.7
  meta: ^1.16.0
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
